export const products = [
  {
    id: 1,
    title: "Modern Sofa",
    img : "product1.png",
    description: "A comfortable and stylish modern sofa.",
    quantity: 0,
    price: 299,
    previous_price: 349,
    measurements: {
      width: "200 cm",
      depth: "90 cm",
      height: "85 cm",
    },
    colors: ["Red", "Blue", "Gray"],
    sku: "SOFA-001",
    category: "Sofa",
    additional_info: {
      packaging: "Flat pack for easy transport",
      details: "Made from high-quality materials.",
    },
    rating: 4.5,
    reviews: [],
    questions: [],
    images: [
      "https://images.pexels.com/photos/2732381/pexels-photo-2732381.jpeg",
      "https://images.pexels.com/photos/2990790/pexels-photo-2990790.jpeg",
      "https://images.pexels.com/photos/2588136/pexels-photo-2588136.jpeg",
      "https://images.pexels.com/photos/1167758/pexels-photo-1167758.jpeg",
      "https://images.pexels.com/photos/2450256/pexels-photo-2450256.jpeg",
    ],
    stock: 10,
  },
  {
    id: 2,
    title: "Classic Leather Sofa",
    img : "product1.png",
    description: "Elegant leather sofa for luxurious living.",
    quantity: 0,
    price: 599,
    previous_price: 649,
    measurements: {
      width: "220 cm",
      depth: "95 cm",
      height: "90 cm",
    },
    colors: ["Black", "Brown", "Cream"],
    sku: "SOFA-002",
    category: "Sofa",
    additional_info: {
      packaging: "Comes assembled.",
      details: "Durable leather upholstery.",
    },
    rating: 4.8,
    reviews: [],
    questions: [],
    images: [
      "https://images.pexels.com/photos/2695023/pexels-photo-2695023.jpeg",
      "https://images.pexels.com/photos/2765071/pexels-photo-2765071.jpeg",
      "https://images.pexels.com/photos/2725550/pexels-photo-2725550.jpeg",
      "https://images.pexels.com/photos/2381343/pexels-photo-2381343.jpeg",
      "https://images.pexels.com/photos/1602207/pexels-photo-1602207.jpeg",
    ],
    stock: 5,
  },
  {
    id: 3,
    title: "Sectional Sofa",
    img : "product1.png",
    description: "Versatile sectional sofa with adjustable chaise.",
    quantity: 0,
    price: 750,
    previous_price: 799,
    measurements: {
      width: "250 cm",
      depth: "95 cm",
      height: "85 cm",
    },
    colors: ["Gray", "Navy", "Beige"],
    sku: "SOFA-003",
    category: "Sofa",
    additional_info: {
      packaging: "Requires minor assembly.",
      details: "Reversible chaise for flexible arrangement.",
    },
    rating: 4.7,
    reviews: [],
    questions: [],
    images: [
      "https://images.pexels.com/photos/2768825/pexels-photo-2768825.jpeg",
      "https://images.pexels.com/photos/3652174/pexels-photo-3652174.jpeg",
      "https://images.pexels.com/photos/2687805/pexels-photo-2687805.jpeg",
      "https://images.pexels.com/photos/1621720/pexels-photo-1621720.jpeg",
      "https://images.pexels.com/photos/3758684/pexels-photo-3758684.jpeg",
    ],
    stock: 8,
  },
  {
    id: 4,
    title: "Convertible Sofa Bed",
    img : "product1.png",
    description: "Sofa that easily converts to a bed.",
    quantity: 0,
    price: 499,
    previous_price: 549,
    measurements: {
      width: "200 cm",
      depth: "90 cm",
      height: "85 cm",
    },
    colors: ["Green", "Gray", "Blue"],
    sku: "SOFA-004",
    category: "Sofa",
    additional_info: {
      packaging: "Flat pack for easy transport",
      details: "Ideal for small spaces.",
    },
    rating: 4.4,
    reviews: [],
    questions: [],
    images: [
      "https://images.pexels.com/photos/3748887/pexels-photo-3748887.jpeg",
      "https://images.pexels.com/photos/4143534/pexels-photo-4143534.jpeg",
      "https://images.pexels.com/photos/4161810/pexels-photo-4161810.jpeg",
      "https://images.pexels.com/photos/2792035/pexels-photo-2792035.jpeg",
      "https://images.pexels.com/photos/4038424/pexels-photo-4038424.jpeg",
    ],
    stock: 12,
  },
  {
    id: 5,
    title: "Luxury Fabric Sofa",
    img : "product1.png",
    description: "High-end fabric sofa for comfort and style.",
    quantity: 0,
    price: 899,
    previous_price: 949,
    measurements: {
      width: "230 cm",
      depth: "95 cm",
      height: "90 cm",
    },
    colors: ["Beige", "Taupe", "Charcoal"],
    sku: "SOFA-005",
    category: "Sofa",
    additional_info: {
      packaging: "Requires minor assembly.",
      details: "Stain-resistant fabric.",
    },
    rating: 4.6,
    reviews: [],
    questions: [],
    images: [
      "https://images.pexels.com/photos/2079834/pexels-photo-2079834.jpeg",
      "https://images.pexels.com/photos/1598376/pexels-photo-1598376.jpeg",
      "https://images.pexels.com/photos/2768832/pexels-photo-2768832.jpeg",
      "https://images.pexels.com/photos/2107306/pexels-photo-2107306.jpeg",
      "https://images.pexels.com/photos/3727464/pexels-photo-3727464.jpeg",
    ],
    stock: 6,
  },
  {
    id: 6,
    title: "Minimalist Chair",
    img : "product1.png",
    description: "Simple and elegant chair for any space.",
    quantity: 0,
    price: 149,
    previous_price: 169,
    measurements: {
      width: "50 cm",
      depth: "50 cm",
      height: "90 cm",
    },
    colors: ["Black", "White", "Wood"],
    sku: "CHAIR-001",
    category: "Chair",
    additional_info: {
      packaging: "Flat pack for easy transport",
      details: "Lightweight and easy to move.",
    },
    rating: 4.3,
    reviews: [],
    questions: [],
    images: [
      "https://images.pexels.com/photos/2132064/pexels-photo-2132064.jpeg",
      "https://images.pexels.com/photos/3732901/pexels-photo-3732901.jpeg",
      "https://images.pexels.com/photos/3990469/pexels-photo-3990469.jpeg",
      "https://images.pexels.com/photos/6509475/pexels-photo-6509475.jpeg",
      "https://images.pexels.com/photos/1739196/pexels-photo-1739196.jpeg",
    ],
    stock: 15,
  },
  {
    id: 7,
    title: "Recliner Chair",
    img : "product1.png",
    description: "Comfortable recliner for ultimate relaxation.",
    quantity: 0,
    price: 399,
    previous_price: 429,
    measurements: {
      width: "80 cm",
      depth: "90 cm",
      height: "100 cm",
    },
    colors: ["Gray", "Brown", "Beige"],
    sku: "CHAIR-002",
    category: "Chair",
    additional_info: {
      packaging: "Requires assembly.",
      details: "Includes a reclining feature.",
    },
    rating: 4.7,
    reviews: [],
    questions: [],
    images: [
      "https://images.pexels.com/photos/2688303/pexels-photo-2688303.jpeg",
      "https://images.pexels.com/photos/1658520/pexels-photo-1658520.jpeg",
      "https://images.pexels.com/photos/2777576/pexels-photo-2777576.jpeg",
      "https://images.pexels.com/photos/2330266/pexels-photo-2330266.jpeg",
      "https://images.pexels.com/photos/3835631/pexels-photo-3835631.jpeg",
    ],
    stock: 8,
  },
  {
    id: 8,
    title: "Wooden Dining Table",
    img : "product1.png",
    description: "Spacious dining table made of solid wood.",
    quantity: 0,
    price: 699,
    previous_price: 749,
    measurements: {
      width: "180 cm",
      depth: "90 cm",
      height: "75 cm",
    },
    colors: ["Natural Wood", "Dark Wood"],
    sku: "TABLE-001",
    category: "Table",
    additional_info: {
      packaging: "Requires assembly.",
      details: "Seats up to 6 people.",
    },
    rating: 4.5,
    reviews: [],
    questions: [],
    images: [
      "https://images.pexels.com/photos/2679002/pexels-photo-2679002.jpeg",
      "https://images.pexels.com/photos/2081662/pexels-photo-2081662.jpeg",
      "https://images.pexels.com/photos/4490326/pexels-photo-4490326.jpeg",
      "https://images.pexels.com/photos/2403378/pexels-photo-2403378.jpeg",
      "https://images.pexels.com/photos/3749184/pexels-photo-3749184.jpeg",
    ],
    stock: 4,
  },
  {
    id: 9,
    title: "Glass Coffee Table",
    img : "product1.png",

    description: "Stylish coffee table with a glass top.",
    quantity: 0,
    price: 299,
    previous_price: 329,
    measurements: {
      width: "100 cm",
      depth: "60 cm",
      height: "40 cm",
    },
    colors: ["Clear", "Black"],
    sku: "TABLE-002",
    category: "Table",
    additional_info: {
      packaging: "Flat pack for easy transport.",
      details: "Easy to clean.",
    },
    rating: 4.2,
    reviews: [],
    questions: [],
    images: [
      "https://images.pexels.com/photos/2212770/pexels-photo-2212770.jpeg",
      "https://images.pexels.com/photos/2658221/pexels-photo-2658221.jpeg",
      "https://images.pexels.com/photos/2611020/pexels-photo-2611020.jpeg",
      "https://images.pexels.com/photos/4117534/pexels-photo-4117534.jpeg",
      "https://images.pexels.com/photos/3094014/pexels-photo-3094014.jpeg",
    ],
    stock: 10,
  },
  {
    id: 10,
    title: "Bar Stool",
    img : "product1.png",

    description: "Modern bar stool with adjustable height.",
    quantity: 0,
    price: 149,
    previous_price: 169,
    measurements: {
      width: "40 cm",
      depth: "40 cm",
      height: "75-95 cm",
    },
    colors: ["Black", "White", "Red"],
    sku: "STOOL-001",
    category: "Stool",
    additional_info: {
      packaging: "Flat pack for easy transport.",
      details: "Perfect for kitchen islands.",
    },
    rating: 4.6,
    reviews: [],
    questions: [],
    images: [
      "https://images.pexels.com/photos/3779677/pexels-photo-3779677.jpeg",
      "https://images.pexels.com/photos/3749125/pexels-photo-3749125.jpeg",
      "https://images.pexels.com/photos/2999665/pexels-photo-2999665.jpeg",
      "https://images.pexels.com/photos/3779668/pexels-photo-3779668.jpeg",
      "https://images.pexels.com/photos/7219580/pexels-photo-7219580.jpeg",
    ],
    stock: 20,
  },
  {
    id: 11,
    title: "Fabric Storage Drawer",
    img : "product1.png",

    description: "Soft fabric drawer for versatile storage.",
    quantity: 0,
    price: 89,
    measurements: {
      width: "30 cm",
      depth: "30 cm",
      height: "30 cm",
    },
    colors: ["Gray", "Blue", "Pink"],
    sku: "DRAWER-005",
    category: "Drawer",
    additional_info: {
      packaging: "Flat pack for easy transport",
      details: "Lightweight and portable.",
    },
    rating: 4.3,
    reviews: [],
    questions: [],
    images: [
      "https://images.pexels.com/photos/2063283/pexels-photo-2063283.jpeg",
      "https://images.pexels.com/photos/2063284/pexels-photo-2063284.jpeg",
      "https://images.pexels.com/photos/2063285/pexels-photo-2063285.jpeg",
      "https://images.pexels.com/photos/2063286/pexels-photo-2063286.jpeg",
      "https://images.pexels.com/photos/2063287/pexels-photo-2063287.jpeg",
    ],
    stock: 20,
  },
  {
    id: 12,
    title: "Table Lamp",
    img : "product1.png",

    description: "Stylish table lamp for your desk.",
    quantity: 0,
    price: 49,
    measurements: {
      width: "25 cm",
      depth: "25 cm",
      height: "60 cm",
    },
    colors: ["Black", "White", "Gold"],
    sku: "LAMP-001",
    category: "Lamp",
    additional_info: {
      packaging: "Requires minor assembly.",
      details: "Energy-efficient LED bulb included.",
    },
    rating: 4.5,
    reviews: [],
    questions: [],
    images: [
      "https://images.pexels.com/photos/1658520/pexels-photo-1658520.jpeg",
      "https://images.pexels.com/photos/4490327/pexels-photo-4490327.jpeg",
      "https://images.pexels.com/photos/4490328/pexels-photo-4490328.jpeg",
      "https://images.pexels.com/photos/4490329/pexels-photo-4490329.jpeg",
      "https://images.pexels.com/photos/4490330/pexels-photo-4490330.jpeg",
    ],
    stock: 25,
  },
  {
    id: 13,
    title: "Floor Lamp",
    img : "product1.png",

    description: "Elegant floor lamp for ambient lighting.",
    quantity: 0,
    price: 89,
    measurements: {
      width: "30 cm",
      depth: "30 cm",
      height: "150 cm",
    },
    colors: ["Black", "Silver", "Brass"],
    sku: "LAMP-002",
    category: "Lamp",
    additional_info: {
      packaging: "Flat pack for easy transport",
      details: "Adjustable height.",
    },
    rating: 4.6,
    reviews: [],
    questions: [],
    images: [
      "https://images.pexels.com/photos/4490331/pexels-photo-4490331.jpeg",
      "https://images.pexels.com/photos/4490332/pexels-photo-4490332.jpeg",
      "https://images.pexels.com/photos/4490333/pexels-photo-4490333.jpeg",
      "https://images.pexels.com/photos/4490334/pexels-photo-4490334.jpeg",
      "https://images.pexels.com/photos/4490335/pexels-photo-4490335.jpeg",
    ],
    stock: 15,
  },
  {
    id: 14,
    title: "Desk Lamp",
    img : "product1.png",

    description: "Compact desk lamp for workspace lighting.",
    quantity: 0,
    price: 39,
    measurements: {
      width: "15 cm",
      depth: "15 cm",
      height: "50 cm",
    },
    colors: ["White", "Gray", "Blue"],
    sku: "LAMP-003",
    category: "Lamp",
    additional_info: {
      packaging: "Requires minor assembly.",
      details: "Includes a dimmable LED bulb.",
    },
    rating: 4.4,
    reviews: [],
    questions: [],
    images: [
      "https://images.pexels.com/photos/4490336/pexels-photo-4490336.jpeg",
      "https://images.pexels.com/photos/4490337/pexels-photo-4490337.jpeg",
      "https://images.pexels.com/photos/4490338/pexels-photo-4490338.jpeg",
      "https://images.pexels.com/photos/4490339/pexels-photo-4490339.jpeg",
      "https://images.pexels.com/photos/4490340/pexels-photo-4490340.jpeg",
    ],
    stock: 30,
  },
  {
    id: 15,
    title: "Nightstand Lamp",
    img : "product1.png",

    description: "Chic nightstand lamp for bedrooms.",
    quantity: 0,
    price: 59,
    measurements: {
      width: "20 cm",
      depth: "20 cm",
      height: "40 cm",
    },
    colors: ["Gold", "Silver", "Bronze"],
    sku: "LAMP-004",
    category: "Lamp",
    additional_info: {
      packaging: "Flat pack for easy transport",
      details: "Perfect for nightstands.",
    },
    rating: 4.5,
    reviews: [],
    questions: [],
    images: [
      "https://images.pexels.com/photos/4490341/pexels-photo-4490341.jpeg",
      "https://images.pexels.com/photos/4490342/pexels-photo-4490342.jpeg",
      "https://images.pexels.com/photos/4490343/pexels-photo-4490343.jpeg",
      "https://images.pexels.com/photos/4490344/pexels-photo-4490344.jpeg",
      "https://images.pexels.com/photos/4490345/pexels-photo-4490345.jpeg",
    ],
    stock: 22,
  },
  {
    id: 16,
    title: "LED Floor Lamp",
    img : "product1.png",

    description: "Modern LED floor lamp for living rooms.",
    quantity: 0,
    price: 129,
    measurements: {
      width: "25 cm",
      depth: "25 cm",
      height: "180 cm",
    },
    colors: ["Black", "White"],
    sku: "LAMP-005",
    category: "Lamp",
    additional_info: {
      packaging: "Flat pack for easy transport",
      details: "Smart lighting features.",
    },
    rating: 4.8,
    reviews: [],
    questions: [],
    images: [
      "https://images.pexels.com/photos/4490346/pexels-photo-4490346.jpeg",
      "https://images.pexels.com/photos/4490347/pexels-photo-4490347.jpeg",
      "https://images.pexels.com/photos/4490348/pexels-photo-4490348.jpeg",
      "https://images.pexels.com/photos/4490349/pexels-photo-4490349.jpeg",
      "https://images.pexels.com/photos/4490350/pexels-photo-4490350.jpeg",
    ],
    stock: 10,
  },
  {
    id: 17,
    title: "Decorative Pillow",
    img : "product1.png",

    description: "Colorful decorative pillow for sofas.",
    quantity: 0,
    price: 29,
    measurements: {
      width: "45 cm",
      depth: "45 cm",
      height: "10 cm",
    },
    colors: ["Red", "Blue", "Green"],
    sku: "PILLOW-001",
    category: "Pillow",
    additional_info: {
      packaging: "Soft and plush.",
      details: "Machine washable cover.",
    },
    rating: 4.5,
    reviews: [],
    questions: [],
    images: [
      "https://images.pexels.com/photos/4490351/pexels-photo-4490351.jpeg",
      "https://images.pexels.com/photos/4490352/pexels-photo-4490352.jpeg",
      "https://images.pexels.com/photos/4490353/pexels-photo-4490353.jpeg",
      "https://images.pexels.com/photos/4490354/pexels-photo-4490354.jpeg",
      "https://images.pexels.com/photos/4490355/pexels-photo-4490355.jpeg",
    ],
    stock: 50,
  },
  {
    id: 18,
    title: "Travel Pillow",
    img : "product1.png",

    description: "Comfortable travel pillow for on-the-go.",
    quantity: 0,
    price: 19,
    measurements: {
      width: "30 cm",
      depth: "30 cm",
      height: "10 cm",
    },
    colors: ["Gray", "Blue", "Black"],
    sku: "PILLOW-002",
    category: "Pillow",
    additional_info: {
      packaging: "Compact and portable.",
      details: "Perfect for travel.",
    },
    rating: 4.3,
    reviews: [],
    questions: [],
    images: [
      "https://images.pexels.com/photos/4490356/pexels-photo-4490356.jpeg",
      "https://images.pexels.com/photos/4490357/pexels-photo-4490357.jpeg",
      "https://images.pexels.com/photos/4490358/pexels-photo-4490358.jpeg",
      "https://images.pexels.com/photos/4490359/pexels-photo-4490359.jpeg",
      "https://images.pexels.com/photos/4490360/pexels-photo-4490360.jpeg",
    ],
    stock: 75,
  },
  {
    id: 19,
    title: "Cushion",
    img : "product1.png",

    description: "Soft cushion for extra comfort.",
    quantity: 0,
    price: 39,
    measurements: {
      width: "40 cm",
      depth: "40 cm",
      height: "15 cm",
    },
    colors: ["Beige", "Brown", "Cream"],
    sku: "CUSHION-001",
    category: "Cushion",
    additional_info: {
      packaging: "Soft and plush.",
      details: "Great for relaxing.",
    },
    rating: 4.6,
    reviews: [],
    questions: [],
    images: [
      "https://images.pexels.com/photos/4490361/pexels-photo-4490361.jpeg",
      "https://images.pexels.com/photos/4490362/pexels-photo-4490362.jpeg",
      "https://images.pexels.com/photos/4490363/pexels-photo-4490363.jpeg",
      "https://images.pexels.com/photos/4490364/pexels-photo-4490364.jpeg",
      "https://images.pexels.com/photos/4490365/pexels-photo-4490365.jpeg",
    ],
    stock: 40,
  },
  {
    id: 20,
    title: "Outdoor Cushion",
    img : "product1.png",

    description: "Durable cushion for outdoor use.",
    quantity: 0,
    price: 49,
    measurements: {
      width: "50 cm",
      depth: "50 cm",
      height: "10 cm",
    },
    colors: ["Turquoise", "Yellow", "Gray"],
    sku: "CUSHION-002",
    category: "Cushion",
    additional_info: {
      packaging: "Weather-resistant material.",
      details: "Great for patios.",
    },
    rating: 4.7,
    reviews: [],
    questions: [],
    images: [
      "https://images.pexels.com/photos/4490366/pexels-photo-4490366.jpeg",
      "https://images.pexels.com/photos/4490367/pexels-photo-4490367.jpeg",
      "https://images.pexels.com/photos/4490368/pexels-photo-4490368.jpeg",
      "https://images.pexels.com/photos/4490369/pexels-photo-4490369.jpeg",
      "https://images.pexels.com/photos/4490370/pexels-photo-4490370.jpeg",
    ],
    stock: 30,
  },
];
